### ISSUE TITLE
Improve synchronous APIs

### ISSUE THREAD

**Issue by stanislav-bedunkevich** [RelationalAI/rai-sdk-csharp#11]
Instead of using `Thread.Sleep(seconds)` we need to migrate toward using polling via the [Polly](https://github.com/App-vNext/Polly) library. This is going to help with resource management and also follow the async/await approach.

This includes adding retry logic to where necessary. This is applicable to the operations that wrap async API and provide a sync version of it.

**Comment by stanislav-bedunkevich** [comment]
Enables https://github.com/RelationalAI/rai-sdk-csharp/issues/10.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6208](https://relationalai.atlassian.net/browse/RAI-6208).

_This link is only accessible to employees of RelationalAI._
