### ISSUE TITLE
Add unit tests!

### ISSUE THREAD

**Issue by larf311** [RelationalAI/rai-sdk-csharp#16]
Set up unit test framework and add at least one unit test.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6372](https://relationalai.atlassian.net/browse/RAI-6372).

_This link is only accessible to employees of RelationalAI._

**Comment by miazamrai** [comment]
@larf311 @NRHelmi Should this be closed as it has been fixed already?

**Comment by NRHelmi** [comment]
thanks @miazamrai, we can close this issue
