### ISSUE TITLE
Prevent PR merges without passing unit tests

### ISSUE THREAD

**Issue by larf311** [RelationalAI/rai-sdk-csharp#17]
Unit tests should run automatically on PR branches. Merging should be prevented unless all unit tests pass.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6373](https://relationalai.atlassian.net/browse/RAI-6373).

_This link is only accessible to employees of RelationalAI._

**Comment by miazamrai** [comment]
@larf311 @NRHelmi Should this issue be closed as it has been fixed already?

**Comment by NRHelmi** [comment]
thanks @miazamrai closing this issue as it has been already fixed
