### ISSUE TITLE
Client.ListEnginesAsync API is throwing exception

### ISSUE THREAD

**Issue by miazamrai** [RelationalAI/rai-sdk-csharp#33]
Client.ListEnginesAsync API is throwing exception that it failed to deserialize the JSON response into Engine entity.
The root cause is that a new engine state has been introduced which is not listed in the EngineState enumeration.

**Comment by miazamrai** [comment]
Fix merged.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6935](https://relationalai.atlassian.net/browse/RAI-6935).

_This link is only accessible to employees of RelationalAI._
