### ISSUE TITLE
The integration test suite should only create one engine & database

### ISSUE THREAD

**Issue by larf311** [RelationalAI/rai-sdk-csharp#45]
Right now each test creates its own engine and database. This is putting too much pressure on the provisioner and we're getting lots of timeouts.

**Comment by miazamrai** [comment]
Issue had been fixed and merged with main.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-7713](https://relationalai.atlassian.net/browse/RAI-7713).

_This link is only accessible to employees of RelationalAI._
